"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetaDataHelper__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "LENGTH_MISMATCH",
        type: "error",
    },
    {
        inputs: [],
        name: "METADATA_TOO_LONG",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "bytes4",
                name: "_idToAdd",
                type: "bytes4",
            },
            {
                internalType: "bytes",
                name: "_dataToAdd",
                type: "bytes",
            },
            {
                internalType: "bytes",
                name: "_originalMetadata",
                type: "bytes",
            },
        ],
        name: "addToMetadata",
        outputs: [
            {
                internalType: "bytes",
                name: "_newMetadata",
                type: "bytes",
            },
        ],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes4[]",
                name: "_ids",
                type: "bytes4[]",
            },
            {
                internalType: "bytes[]",
                name: "_metadatas",
                type: "bytes[]",
            },
        ],
        name: "createMetadata",
        outputs: [
            {
                internalType: "bytes",
                name: "_metadata",
                type: "bytes",
            },
        ],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "bytes4",
                name: "_id",
                type: "bytes4",
            },
            {
                internalType: "bytes",
                name: "_metadata",
                type: "bytes",
            },
        ],
        name: "getMetadata",
        outputs: [
            {
                internalType: "bytes",
                name: "_targetMetadata",
                type: "bytes",
            },
        ],
        stateMutability: "pure",
        type: "function",
    },
];
class MetaDataHelper__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.MetaDataHelper__factory = MetaDataHelper__factory;
MetaDataHelper__factory.abi = _abi;
